name: flutter_meeting_app
description: "Flutter移动视频会议应用 - 集成LiveKit和现有PHP后端"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.8.0+1

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # UI框架
  cupertino_icons: ^1.0.6

  # LiveKit视频会议SDK
  livekit_client: ^1.5.2
  flutter_webrtc: 0.9.45

  # 网络请求
  dio: ^5.3.2

  # 权限管理
  permission_handler: ^10.4.3

  # 本地存储
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.1.1

  # 摄像头控制
  camera: ^0.10.5+5

  # 工具类
  path_provider: ^2.1.1
  connectivity_plus: ^4.0.2

  # UI组件
  fluttertoast: ^8.2.4

  # 热更新功能
  ota_update: ^5.0.1
  package_info_plus: ^5.0.1
  
  # 文件打开功能
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

